name: Jira Integration

on:
  pull_request:
    types: [opened, reopened, edited, closed]

jobs:
  jira-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira Issue Key
        id: extract_jira_key
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "Checking PR title: $PR_TITLE"
          echo "Checking PR branch: $PR_BRANCH"
          
          PATTERN="([A-Z]+-[0-9]+)"
          if [[ $PR_TITLE =~ $PATTERN ]]; then
            JIRA_ISSUE="${BASH_REMATCH[1]}"
          elif [[ $PR_BRANCH =~ $PATTERN ]]; then
            JIRA_ISSUE="${BASH_REMATCH[1]}"
          fi
          
          if [[ -n "$JIRA_ISSUE" ]]; then
            echo "Found Jira issue key: $JIRA_ISSUE"
            echo "jira_issue=${JIRA_ISSUE}" >> $GITHUB_OUTPUT
            echo "jira_issue_found=true" >> $GITHUB_OUTPUT
          else
            echo "No Jira issue key found in PR title or branch name"
            echo "jira_issue_found=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Check Jira Issue Status
        if: ${{ steps.extract_jira_key.outputs.jira_issue_found == 'true' }}
        run: |
          JIRA_BASE_URL="${{ secrets.JIRA_BASE_URL }}"
          JIRA_EMAIL="${{ secrets.JIRA_USER_EMAIL }}"
          JIRA_TOKEN="${{ secrets.JIRA_API_TOKEN }}"
          JIRA_ISSUE="${{ steps.extract_jira_key.outputs.jira_issue }}"
          
          echo "GitHub event action: ${{ github.event.action }}"
          echo "PR merged: ${{ github.event.pull_request.merged }}"
          echo "Jira Issue: $JIRA_ISSUE"
          echo "Jira URL: $JIRA_BASE_URL/browse/$JIRA_ISSUE"
          
          # Create auth header
          AUTH=$(echo -n "${JIRA_EMAIL}:${JIRA_TOKEN}" | base64)
          
          # Test authentication
          echo "Testing Jira API authentication..."
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Basic ${AUTH}" "${JIRA_BASE_URL}/rest/api/3/myself")
          echo "Authentication status: $STATUS_CODE"
          
          # Get issue details
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "PR was merged, updating Jira issue to 'In Review'"
            # Transition to "In Review" (ID 41 from previous testing)
            curl -s -X POST \
              -H "Authorization: Basic ${AUTH}" \
              -H "Content-Type: application/json" \
              --data '{"transition":{"id":"41"}}' \
              "${JIRA_BASE_URL}/rest/api/3/issue/${JIRA_ISSUE}/transitions"
          fi
        shell: bash
