name: Jira Integration Test

on:
  pull_request:
    types: [opened, reopened, edited, closed]

jobs:
  jira-integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira Issue Key
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "Checking PR title: $PR_TITLE"
          echo "Checking PR branch: $PR_BRANCH"
          
          PATTERN="([A-Z]+-[0-9]+)"
          if [[ $PR_TITLE =~ $PATTERN ]]; then
            JIRA_ISSUE="${BASH_REMATCH[1]}"
          elif [[ $PR_BRANCH =~ $PATTERN ]]; then
            JIRA_ISSUE="${BASH_REMATCH[1]}"
          fi
          
          if [[ -n "$JIRA_ISSUE" ]]; then
            echo "Found Jira issue key: $JIRA_ISSUE"
            echo "JIRA_ISSUE=$JIRA_ISSUE" >> $GITHUB_ENV
            echo "::set-output name=jira_issue::$JIRA_ISSUE"
          else
            echo "No Jira issue key found in PR title or branch name"
          fi
        shell: bash
      
      - name: Check PR Status
        run: |
          echo "GitHub event action: ${{ github.event.action }}"
          echo "PR merged: ${{ github.event.pull_request.merged }}"
          
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "PR was merged, would update Jira issue to 'In Review'"
          fi
        shell: bash
